{{- if .Values.evaluationApi.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: willow-evaluation-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "willow.labels" . | nindent 4 }}
    app.kubernetes.io/component: evaluation-api
spec:
  type: {{ .Values.evaluationApi.service.type }}
  ports:
    - port: {{ .Values.evaluationApi.service.port }}
      targetPort: {{ .Values.evaluationApi.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "willow.evaluationApi.selectorLabels" . | nindent 4 }}
{{- end }}
