{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: willow-postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "willow.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgresql.password | b64enc | quote }}
{{- end }}

{{- if .Values.evaluationApi.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: willow-evaluation-api-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "willow.labels" . | nindent 4 }}
    app.kubernetes.io/component: evaluation-api
type: Opaque
data:
  API_KEY: {{ .Values.secrets.evaluationApi.apiKey | b64enc | quote }}
{{- end }}

{{- if .Values.adminApi.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: willow-admin-api-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "willow.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-api
type: Opaque
data:
  API_KEY: {{ .Values.secrets.adminApi.apiKey | b64enc | quote }}
  ConnectionStrings__Postgres: {{ printf "%sPassword=%s;" .Values.configMaps.adminApi.ConnectionStrings__Postgres .Values.secrets.postgresql.password | b64enc | quote }}
{{- end }}
